---
title: "eda"
output: html_document
---


```{r}
library(tidyverse)
```


```{r}
# library(tidycensus)
# vars <- load_variables(2016, "acs5", cache = TRUE)
# cacs <- get_acs(
#   geography = "county",
#   year = 2016,
#   survey = "acs5",
#   variables = c(
#     
#     # Poverty
#     pov_total = "B17001_001",
#     pov_below = "B17001_002",
#     
#     # Race
#     race_total = "B03002_001",
#     white_nonhisp = "B03002_003",
#     
#     # Age total
#     age_total = "B01001_001",
#     
#     # Male 65+
#     m65_66 = "B01001_020",
#     m67_69 = "B01001_021",
#     m70_74 = "B01001_022",
#     m75_79 = "B01001_023",
#     m80_84 = "B01001_024",
#     m85p   = "B01001_025",
#     
#     # Female 65+
#     f65_66 = "B01001_044",
#     f67_69 = "B01001_045",
#     f70_74 = "B01001_046",
#     f75_79 = "B01001_047",
#     f80_84 = "B01001_048",
#     f85p   = "B01001_049"
#   )
# )
# 
# saveRDS(cacs, "../data/cacs.csv")
```


```{r}
cacs <- readRDS("../data/cacs.csv")
cacs_wide <- cacs %>%
  select(GEOID, NAME, variable, estimate) %>%
  pivot_wider(names_from = variable, values_from = estimate) %>%
  mutate(
    poverty_rate = pov_below / pov_total,
    nonwhite_rate = 1 - white_nonhisp / race_total,
    age65plus = (
      m65_66 + m67_69 + m70_74 + m75_79 + m80_84 + m85p +
      f65_66 + f67_69 + f70_74 + f75_79 + f80_84 + f85p
    ) / age_total
  ) %>%
  select(GEOID, poverty_rate, nonwhite_rate, age65plus)
cacs_wide$STFIPS <- as.integer(substr(cacs_wide$GEOID, 1, nchar(cacs_wide$GEOID) - 3))
cacs_wide$CTYFIPS <- as.integer(substr(cacs_wide$GEOID, nchar(cacs_wide$GEOID) - 3 + 1, nchar(cacs_wide$GEOID)))

cvd <- read.csv('../data/cvd.csv')
cvd$STFIPS <- as.integer(substr(cvd$County.Code, 1, nchar(cvd$County.Code) - 3))
cvd$CTYFIPS <- as.integer(substr(cvd$County.Code, nchar(cvd$County.Code) - 3 + 1, nchar(cacs_wide$GEOID)))

expansion <- read.csv('../data/expansion_modified.csv')
expansion <- expansion[-c(1, 53:69), ]



# places <- read.csv('../data/places.csv')

uninsurance <- read.csv('../data/uninsurance.csv')
uninsurance <- uninsurance %>% 
  filter(Year == 2016)
uninsurance <- uninsurance[-c(1:51), ]
uninsurance$STFIPS <- as.integer(substr(uninsurance$ID, 1, nchar(uninsurance$ID) - 3))
uninsurance$CTYFIPS <- as.integer(substr(uninsurance$ID, nchar(uninsurance$ID) - 3 + 1, nchar(cacs_wide$GEOID)))

urban <- read.csv('../data/urban.csv')

```


```{r}
df_list <- list(cacs_wide, cvd, uninsurance, urban)
df <- df_list %>%
  reduce(inner_join, by = c("STFIPS", "CTYFIPS"))
(df %>% select(STFIPS, CTYFIPS))[duplicated((df %>% select(STFIPS, CTYFIPS))), ]
df <- inner_join(df, expansion, by = 'STFIPS') %>%
  select(GEOID, poverty_rate, nonwhite_rate, age65plus, Age.Adjusted.Rate, Pct, 
         CODE2013, medicaid_expansion_status) %>%
  filter((Age.Adjusted.Rate != 'Suppressed') & 
           !grepl('Unreliable', Age.Adjusted.Rate)) %>%
  mutate(cvd = as.numeric(Age.Adjusted.Rate),
         uninsurance = Pct / 100,
         rurality = factor(CODE2013, 
                             ordered = TRUE, 
                             levels = c(1, 2, 3, 4, 5, 6)),
         medicaid = factor(medicaid_expansion_status)
         ) %>%
  select(-c(Age.Adjusted.Rate, Pct, CODE2013, medicaid_expansion_status))
```


```{r}
loess_fit <- loess(cvd ~ poverty_rate, df)
x_grid <- seq(min(df$poverty_rate), max(df$poverty_rate), length = 200)
y_hat <- predict(loess_fit, newdata = data.frame(poverty_rate = x_grid))
plot(df$poverty_rate, df$cvd, pch = 16)
lines(x_grid, y_hat, col = "blue", lwd = 2)

```

```{r}
n <- nrow(df)
l <- as.matrix(df %>% select(nonwhite_rate, age65plus, uninsurance,
                             rurality, medicaid))
a <- df$poverty_rate
y <- df$cvd
a.min <- min(df$poverty_rate); a.max <- max(df$poverty_rate)
a.vals <- seq(a.min, a.max, length.out=100)


# leave-one-out cross-validation to select bandwidth
library(KernSmooth)
kern <- function(x) dnorm(x)
w.fn <- function(bw) {
  w.avals <- NULL
  for (a.val in a.vals) {
    a.std <- (a - a.val) / bw
    kern.std <- kern(a.std) / bw
    w.avals <- c(w.avals, mean(a.std ^ 2 * kern.std) * (kern(0) / bw) /
                   (mean(kern.std) * mean(a.std ^ 2 * kern.std) - 
                      mean(a.std * kern.std) ^ 2))
  }
  return(w.avals/n)
}
hatvals <- function(bw) {
  approx(a.vals, w.fn(bw), xout=a)$y
}
cts.eff <- function(out, bw) {
  approx(locpoly(x = a, y = out, bandwidth = bw), xout=a)$y
}
h.fn <- function(h) {
  hats <- hatvals(h)
  mean(((y - cts.eff(y, bw=h)) / (1 - hats)) ^ 2)
}
h.opt <- optimize(h.fn, c(0.01, 50), tol=0.01)$minimum

# estimate variation curve with optimal bandwidth
est <- approx(locpoly(a, y, bandwidth=h.opt), xout = a.vals)$y

# estimate sandwich-style pointwise confidence band
se <- NULL
for (a.val in a.vals) {
  
}
```


```{r}
# set up evaluation points & matrices for predictions

la.new <- rbind(cbind(l, a), cbind(l[rep(1:n, length(a.vals)), ], 
                                   a = rep(a.vals, rep(n, length(a.vals)))))
l.new <- la.new[,-dim(la.new)]

# fit super learner
sl.lib <- c("SL.earth", "SL.gam", "SL.gbm", "SL.glm", "SL.glmnet")
pimod <- SupeLearner(Y=a, X=l, SL.library=sl.lib, newX=l.new)
pimod.vals <-
```

